// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	User
	UserId
	Task
	TaskId
	Billing
	BillingId
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id      int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Utype   string `protobuf:"bytes,3,opt,name=utype" json:"utype,omitempty"`
	Balance int32  `protobuf:"varint,4,opt,name=balance" json:"balance,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetUtype() string {
	if m != nil {
		return m.Utype
	}
	return ""
}

func (m *User) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type UserId struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *UserId) Reset()                    { *m = UserId{} }
func (m *UserId) String() string            { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()               {}
func (*UserId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Task struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Price       int32  `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	Status      string `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Task) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Task) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type TaskId struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *TaskId) Reset()                    { *m = TaskId{} }
func (m *TaskId) String() string            { return proto.CompactTextString(m) }
func (*TaskId) ProtoMessage()               {}
func (*TaskId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TaskId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Billing struct {
	Id       int64                       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Sender   string                      `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	Reciever string                      `protobuf:"bytes,3,opt,name=reciever" json:"reciever,omitempty"`
	Amount   int32                       `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	TimeBill *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=time_bill,json=timeBill" json:"time_bill,omitempty"`
	TaskId   int32                       `protobuf:"varint,6,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Btype    string                      `protobuf:"bytes,7,opt,name=btype" json:"btype,omitempty"`
}

func (m *Billing) Reset()                    { *m = Billing{} }
func (m *Billing) String() string            { return proto.CompactTextString(m) }
func (*Billing) ProtoMessage()               {}
func (*Billing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Billing) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Billing) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Billing) GetReciever() string {
	if m != nil {
		return m.Reciever
	}
	return ""
}

func (m *Billing) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Billing) GetTimeBill() *google_protobuf1.Timestamp {
	if m != nil {
		return m.TimeBill
	}
	return nil
}

func (m *Billing) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Billing) GetBtype() string {
	if m != nil {
		return m.Btype
	}
	return ""
}

type BillingId struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *BillingId) Reset()                    { *m = BillingId{} }
func (m *BillingId) String() string            { return proto.CompactTextString(m) }
func (*BillingId) ProtoMessage()               {}
func (*BillingId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BillingId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*UserId)(nil), "api.UserId")
	proto.RegisterType((*Task)(nil), "api.Task")
	proto.RegisterType((*TaskId)(nil), "api.TaskId")
	proto.RegisterType((*Billing)(nil), "api.Billing")
	proto.RegisterType((*BillingId)(nil), "api.BillingId")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DoUsers service

type DoUsersClient interface {
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserId, error)
	SelectUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *User, opts ...grpc.CallOption) (DoUsers_ListUsersClient, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error)
}

type doUsersClient struct {
	cc *grpc.ClientConn
}

func NewDoUsersClient(cc *grpc.ClientConn) DoUsersClient {
	return &doUsersClient{cc}
}

func (c *doUsersClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserId, error) {
	out := new(UserId)
	err := grpc.Invoke(ctx, "/api.DoUsers/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doUsersClient) SelectUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/api.DoUsers/SelectUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doUsersClient) ListUsers(ctx context.Context, in *User, opts ...grpc.CallOption) (DoUsers_ListUsersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DoUsers_serviceDesc.Streams[0], c.cc, "/api.DoUsers/ListUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &doUsersListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DoUsers_ListUsersClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type doUsersListUsersClient struct {
	grpc.ClientStream
}

func (x *doUsersListUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *doUsersClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/api.DoUsers/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doUsersClient) DeleteUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/api.DoUsers/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DoUsers service

type DoUsersServer interface {
	CreateUser(context.Context, *User) (*UserId, error)
	SelectUser(context.Context, *UserId) (*User, error)
	ListUsers(*User, DoUsers_ListUsersServer) error
	UpdateUser(context.Context, *User) (*User, error)
	DeleteUser(context.Context, *UserId) (*User, error)
}

func RegisterDoUsersServer(s *grpc.Server, srv DoUsersServer) {
	s.RegisterService(&_DoUsers_serviceDesc, srv)
}

func _DoUsers_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoUsersServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoUsers/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoUsersServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoUsers_SelectUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoUsersServer).SelectUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoUsers/SelectUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoUsersServer).SelectUser(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoUsers_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(User)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DoUsersServer).ListUsers(m, &doUsersListUsersServer{stream})
}

type DoUsers_ListUsersServer interface {
	Send(*User) error
	grpc.ServerStream
}

type doUsersListUsersServer struct {
	grpc.ServerStream
}

func (x *doUsersListUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _DoUsers_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoUsersServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoUsers/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoUsersServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoUsers_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoUsersServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoUsers/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoUsersServer).DeleteUser(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

var _DoUsers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DoUsers",
	HandlerType: (*DoUsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _DoUsers_CreateUser_Handler,
		},
		{
			MethodName: "SelectUser",
			Handler:    _DoUsers_SelectUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _DoUsers_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _DoUsers_DeleteUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _DoUsers_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

// Client API for DoTasks service

type DoTasksClient interface {
	CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskId, error)
	SelectTask(ctx context.Context, in *TaskId, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *Task, opts ...grpc.CallOption) (DoTasks_ListTasksClient, error)
	UpdateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error)
	DeleteTask(ctx context.Context, in *TaskId, opts ...grpc.CallOption) (*Task, error)
}

type doTasksClient struct {
	cc *grpc.ClientConn
}

func NewDoTasksClient(cc *grpc.ClientConn) DoTasksClient {
	return &doTasksClient{cc}
}

func (c *doTasksClient) CreateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskId, error) {
	out := new(TaskId)
	err := grpc.Invoke(ctx, "/api.DoTasks/CreateTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doTasksClient) SelectTask(ctx context.Context, in *TaskId, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := grpc.Invoke(ctx, "/api.DoTasks/SelectTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doTasksClient) ListTasks(ctx context.Context, in *Task, opts ...grpc.CallOption) (DoTasks_ListTasksClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DoTasks_serviceDesc.Streams[0], c.cc, "/api.DoTasks/ListTasks", opts...)
	if err != nil {
		return nil, err
	}
	x := &doTasksListTasksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DoTasks_ListTasksClient interface {
	Recv() (*Task, error)
	grpc.ClientStream
}

type doTasksListTasksClient struct {
	grpc.ClientStream
}

func (x *doTasksListTasksClient) Recv() (*Task, error) {
	m := new(Task)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *doTasksClient) UpdateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := grpc.Invoke(ctx, "/api.DoTasks/UpdateTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doTasksClient) DeleteTask(ctx context.Context, in *TaskId, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := grpc.Invoke(ctx, "/api.DoTasks/DeleteTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DoTasks service

type DoTasksServer interface {
	CreateTask(context.Context, *Task) (*TaskId, error)
	SelectTask(context.Context, *TaskId) (*Task, error)
	ListTasks(*Task, DoTasks_ListTasksServer) error
	UpdateTask(context.Context, *Task) (*Task, error)
	DeleteTask(context.Context, *TaskId) (*Task, error)
}

func RegisterDoTasksServer(s *grpc.Server, srv DoTasksServer) {
	s.RegisterService(&_DoTasks_serviceDesc, srv)
}

func _DoTasks_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoTasksServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoTasks/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoTasksServer).CreateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoTasks_SelectTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoTasksServer).SelectTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoTasks/SelectTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoTasksServer).SelectTask(ctx, req.(*TaskId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoTasks_ListTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Task)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DoTasksServer).ListTasks(m, &doTasksListTasksServer{stream})
}

type DoTasks_ListTasksServer interface {
	Send(*Task) error
	grpc.ServerStream
}

type doTasksListTasksServer struct {
	grpc.ServerStream
}

func (x *doTasksListTasksServer) Send(m *Task) error {
	return x.ServerStream.SendMsg(m)
}

func _DoTasks_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoTasksServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoTasks/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoTasksServer).UpdateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoTasks_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoTasksServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoTasks/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoTasksServer).DeleteTask(ctx, req.(*TaskId))
	}
	return interceptor(ctx, in, info, handler)
}

var _DoTasks_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DoTasks",
	HandlerType: (*DoTasksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _DoTasks_CreateTask_Handler,
		},
		{
			MethodName: "SelectTask",
			Handler:    _DoTasks_SelectTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _DoTasks_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _DoTasks_DeleteTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListTasks",
			Handler:       _DoTasks_ListTasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

// Client API for DoBillings service

type DoBillingsClient interface {
	CreateBilling(ctx context.Context, in *Billing, opts ...grpc.CallOption) (*BillingId, error)
	SelectBilling(ctx context.Context, in *BillingId, opts ...grpc.CallOption) (*Billing, error)
	ListBillings(ctx context.Context, in *Billing, opts ...grpc.CallOption) (DoBillings_ListBillingsClient, error)
	UpdateBilling(ctx context.Context, in *Billing, opts ...grpc.CallOption) (*Billing, error)
	DeleteBilling(ctx context.Context, in *BillingId, opts ...grpc.CallOption) (*Billing, error)
}

type doBillingsClient struct {
	cc *grpc.ClientConn
}

func NewDoBillingsClient(cc *grpc.ClientConn) DoBillingsClient {
	return &doBillingsClient{cc}
}

func (c *doBillingsClient) CreateBilling(ctx context.Context, in *Billing, opts ...grpc.CallOption) (*BillingId, error) {
	out := new(BillingId)
	err := grpc.Invoke(ctx, "/api.DoBillings/CreateBilling", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doBillingsClient) SelectBilling(ctx context.Context, in *BillingId, opts ...grpc.CallOption) (*Billing, error) {
	out := new(Billing)
	err := grpc.Invoke(ctx, "/api.DoBillings/SelectBilling", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doBillingsClient) ListBillings(ctx context.Context, in *Billing, opts ...grpc.CallOption) (DoBillings_ListBillingsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DoBillings_serviceDesc.Streams[0], c.cc, "/api.DoBillings/ListBillings", opts...)
	if err != nil {
		return nil, err
	}
	x := &doBillingsListBillingsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DoBillings_ListBillingsClient interface {
	Recv() (*Billing, error)
	grpc.ClientStream
}

type doBillingsListBillingsClient struct {
	grpc.ClientStream
}

func (x *doBillingsListBillingsClient) Recv() (*Billing, error) {
	m := new(Billing)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *doBillingsClient) UpdateBilling(ctx context.Context, in *Billing, opts ...grpc.CallOption) (*Billing, error) {
	out := new(Billing)
	err := grpc.Invoke(ctx, "/api.DoBillings/UpdateBilling", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doBillingsClient) DeleteBilling(ctx context.Context, in *BillingId, opts ...grpc.CallOption) (*Billing, error) {
	out := new(Billing)
	err := grpc.Invoke(ctx, "/api.DoBillings/DeleteBilling", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DoBillings service

type DoBillingsServer interface {
	CreateBilling(context.Context, *Billing) (*BillingId, error)
	SelectBilling(context.Context, *BillingId) (*Billing, error)
	ListBillings(*Billing, DoBillings_ListBillingsServer) error
	UpdateBilling(context.Context, *Billing) (*Billing, error)
	DeleteBilling(context.Context, *BillingId) (*Billing, error)
}

func RegisterDoBillingsServer(s *grpc.Server, srv DoBillingsServer) {
	s.RegisterService(&_DoBillings_serviceDesc, srv)
}

func _DoBillings_CreateBilling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Billing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoBillingsServer).CreateBilling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoBillings/CreateBilling",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoBillingsServer).CreateBilling(ctx, req.(*Billing))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoBillings_SelectBilling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillingId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoBillingsServer).SelectBilling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoBillings/SelectBilling",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoBillingsServer).SelectBilling(ctx, req.(*BillingId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoBillings_ListBillings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Billing)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DoBillingsServer).ListBillings(m, &doBillingsListBillingsServer{stream})
}

type DoBillings_ListBillingsServer interface {
	Send(*Billing) error
	grpc.ServerStream
}

type doBillingsListBillingsServer struct {
	grpc.ServerStream
}

func (x *doBillingsListBillingsServer) Send(m *Billing) error {
	return x.ServerStream.SendMsg(m)
}

func _DoBillings_UpdateBilling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Billing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoBillingsServer).UpdateBilling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoBillings/UpdateBilling",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoBillingsServer).UpdateBilling(ctx, req.(*Billing))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoBillings_DeleteBilling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillingId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoBillingsServer).DeleteBilling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DoBillings/DeleteBilling",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoBillingsServer).DeleteBilling(ctx, req.(*BillingId))
	}
	return interceptor(ctx, in, info, handler)
}

var _DoBillings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DoBillings",
	HandlerType: (*DoBillingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBilling",
			Handler:    _DoBillings_CreateBilling_Handler,
		},
		{
			MethodName: "SelectBilling",
			Handler:    _DoBillings_SelectBilling_Handler,
		},
		{
			MethodName: "UpdateBilling",
			Handler:    _DoBillings_UpdateBilling_Handler,
		},
		{
			MethodName: "DeleteBilling",
			Handler:    _DoBillings_DeleteBilling_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBillings",
			Handler:       _DoBillings_ListBillings_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 632 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0xdd, 0x3c, 0xea, 0xdb, 0x24, 0xd0, 0xa1, 0xb4, 0xc6, 0x20, 0x11, 0xcd, 0x2a, 0xca,
	0x22, 0x41, 0x65, 0x81, 0x54, 0x75, 0x45, 0xab, 0xaa, 0x95, 0x58, 0x99, 0x76, 0xc3, 0xa6, 0x1a,
	0xc7, 0xd3, 0x68, 0x54, 0xc7, 0xb6, 0x3c, 0x13, 0x24, 0x84, 0xd8, 0xf0, 0x0b, 0xfc, 0x0b, 0x7f,
	0xc1, 0x8a, 0x5f, 0xe0, 0x17, 0xd8, 0xa3, 0x3b, 0x33, 0x71, 0xfd, 0x88, 0x04, 0xec, 0xe6, 0x4c,
	0xe6, 0x9c, 0x7b, 0xee, 0xb9, 0xd7, 0x01, 0x8f, 0xe5, 0x62, 0x96, 0x17, 0x99, 0xca, 0xc8, 0x0e,
	0xcb, 0x45, 0xf0, 0x62, 0x99, 0x65, 0xcb, 0x84, 0xcf, 0x59, 0x2e, 0xe6, 0x2c, 0x4d, 0x33, 0xc5,
	0x94, 0xc8, 0x52, 0x69, 0x9e, 0x04, 0x2f, 0xed, 0xaf, 0x1a, 0x45, 0xeb, 0xbb, 0xb9, 0x12, 0x2b,
	0x2e, 0x15, 0x5b, 0xe5, 0xe6, 0x01, 0xfd, 0x00, 0x9d, 0x1b, 0xc9, 0x0b, 0x32, 0x02, 0x57, 0xc4,
	0xbe, 0x33, 0x76, 0x26, 0x3b, 0xa1, 0x2b, 0x62, 0x42, 0xa0, 0x93, 0xb2, 0x15, 0xf7, 0xdd, 0xb1,
	0x33, 0xf1, 0x42, 0x7d, 0x26, 0x07, 0xd0, 0x5d, 0xab, 0x4f, 0x39, 0xf7, 0x77, 0xf4, 0xa5, 0x01,
	0xc4, 0x87, 0x7e, 0xc4, 0x12, 0x96, 0x2e, 0xb8, 0xdf, 0x19, 0x3b, 0x93, 0x6e, 0xb8, 0x81, 0xd4,
	0x87, 0x1e, 0x6a, 0x5f, 0xc5, 0x4d, 0x75, 0x7a, 0x07, 0x9d, 0x6b, 0x26, 0xef, 0x5b, 0x55, 0xc7,
	0xb0, 0x17, 0x73, 0xb9, 0x28, 0x44, 0x8e, 0x4d, 0xd8, 0xe2, 0xd5, 0x2b, 0xf4, 0x90, 0x17, 0x62,
	0x61, 0x3c, 0x74, 0x43, 0x03, 0xc8, 0x21, 0xf4, 0xa4, 0x62, 0x6a, 0x2d, 0xb5, 0x05, 0x2f, 0xb4,
	0x08, 0x1d, 0x60, 0x9d, 0x2d, 0x0e, 0x7e, 0x38, 0xd0, 0x7f, 0x2b, 0x92, 0x44, 0xa4, 0xcb, 0x96,
	0x0b, 0x54, 0xe3, 0x69, 0xcc, 0x0b, 0x6b, 0xc0, 0x22, 0x12, 0xc0, 0x6e, 0xc1, 0x17, 0x82, 0x7f,
	0xe4, 0x85, 0x8d, 0xa0, 0xc4, 0xc8, 0x61, 0xab, 0x6c, 0x9d, 0x2a, 0x1b, 0x82, 0x45, 0xe4, 0x0d,
	0x78, 0x18, 0xf9, 0x6d, 0x24, 0x92, 0xc4, 0xef, 0x8e, 0x9d, 0xc9, 0xde, 0x71, 0x30, 0x33, 0x43,
	0x99, 0x6d, 0x86, 0x32, 0xbb, 0xde, 0x0c, 0x25, 0xdc, 0xc5, 0xc7, 0xe8, 0x8b, 0x1c, 0x41, 0x5f,
	0x31, 0x79, 0x7f, 0x2b, 0x62, 0xbf, 0x67, 0x14, 0x95, 0xe9, 0xe4, 0x00, 0xba, 0x91, 0x9e, 0x42,
	0xdf, 0x4c, 0x41, 0x03, 0xfa, 0x1c, 0x3c, 0xdb, 0x4e, 0xbb, 0xd9, 0xe3, 0xef, 0x2e, 0xf4, 0xcf,
	0x33, 0x9c, 0x85, 0x24, 0x27, 0x00, 0x67, 0x05, 0x67, 0x8a, 0xeb, 0xb1, 0x7b, 0x33, 0x5c, 0x27,
	0x3c, 0x06, 0x7b, 0xe5, 0xf1, 0x2a, 0xa6, 0x07, 0x5f, 0x7f, 0xfe, 0xfa, 0xe6, 0x8e, 0xa8, 0xa7,
	0xf7, 0x6a, 0x2d, 0x79, 0x71, 0xe2, 0x4c, 0xc9, 0x29, 0xc0, 0x7b, 0x9e, 0xf0, 0x85, 0xd2, 0xdc,
	0x2a, 0x21, 0x78, 0x10, 0xa2, 0x87, 0x9a, 0xfb, 0x98, 0x8c, 0x4a, 0xee, 0xfc, 0xb3, 0x88, 0xbf,
	0x60, 0x14, 0xef, 0x84, 0x54, 0xc6, 0x46, 0xa5, 0x70, 0x85, 0x4a, 0x34, 0x75, 0x40, 0xa0, 0xa4,
	0xca, 0x57, 0x0e, 0x5a, 0xbe, 0xc9, 0xe3, 0x2d, 0x96, 0xdb, 0x45, 0x69, 0xb3, 0xe8, 0x29, 0xc0,
	0x39, 0x4f, 0xb8, 0xe5, 0xfe, 0xc5, 0xf2, 0xb4, 0xc1, 0xb6, 0xc1, 0xe1, 0x0a, 0x55, 0x82, 0xd3,
	0x9b, 0x6b, 0xc8, 0x78, 0xb4, 0xc1, 0x99, 0x3d, 0x6b, 0x04, 0x87, 0x23, 0xab, 0x05, 0xa7, 0xb9,
	0x55, 0x42, 0xf0, 0x20, 0xd4, 0x08, 0x0e, 0xb9, 0xb5, 0xe0, 0x8c, 0x8d, 0x4a, 0xe1, 0x0a, 0xb5,
	0x1e, 0x1c, 0x52, 0x6b, 0xc1, 0x35, 0x2d, 0xb7, 0x8b, 0xd2, 0x66, 0xd1, 0x32, 0xb8, 0x7f, 0xb1,
	0x3c, 0x6d, 0xb0, 0x8f, 0x7f, 0xbb, 0x00, 0xe7, 0x99, 0xdd, 0x48, 0x49, 0x2e, 0x60, 0x68, 0xb2,
	0xdb, 0x7c, 0x72, 0x03, 0x2d, 0x61, 0x51, 0x30, 0xaa, 0xa2, 0xab, 0x98, 0x1e, 0x69, 0xd5, 0x7d,
	0x3a, 0xd0, 0xaa, 0x91, 0xb9, 0xc7, 0x1c, 0x2f, 0x61, 0x68, 0x72, 0x2c, 0x3f, 0xdd, 0x3a, 0x33,
	0xa8, 0xe9, 0xd2, 0x67, 0x5a, 0xe7, 0x09, 0xd9, 0xaf, 0xea, 0x98, 0xf6, 0xce, 0x60, 0x80, 0x99,
	0x96, 0x0e, 0xeb, 0x86, 0xea, 0x32, 0x4f, 0xb5, 0xcc, 0x23, 0x32, 0xac, 0xca, 0x60, 0xbe, 0x17,
	0x30, 0x34, 0xf9, 0x6e, 0x6f, 0x6b, 0xab, 0x19, 0xba, 0xc5, 0xcc, 0x25, 0x0c, 0x4d, 0xd6, 0xff,
	0xd5, 0xd6, 0xb4, 0xad, 0x14, 0xf5, 0xf4, 0x7f, 0xca, 0xeb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x64, 0x9c, 0x09, 0xa5, 0x26, 0x06, 0x00, 0x00,
}
